### ISSUE TITLE
remove 1000 files limit

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/aws-s3-extractor#20]
maximum should not be enforced and the default should be to download all

waits for https://github.com/keboola/php-db-import/issues/39

**Comment by ondrejhlavacek** [comment]
No a napadá tě kolik? Možná bych to neomezoval a dal tam jen časovej timeout.

**Comment by Halama** [comment]
Netuším:) časovej timeout myslíš na komponentě? ok

**Comment by ondrejhlavacek** [comment]
Jj
