### ISSUE TITLE
Cross-account support

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/aws-s3-extractor#24]
viz. https://keboola.slack.com/archives/C038GALTH/p1532426206000247

- my nebo náš klient jim dáme id našeho AWS accountu 
- oni vytvoří u nich roli `arn:aws:iam::794878508631:role/<ROLE_NAME>` které nastaví náš aws account jako a pošlou nám ji
- my vytvoříme ty credentials a povolíme jim assumeRole nad `arn:aws:iam::794878508631:role/<ROLE_NAME>`

- pro použití např. u https://apidocs.mediamath.com/v1/log-level-data-service/overview#data-security-and-authorization

**Comment by Halama** [comment]
Probrali jsme na offsite:

> Klient dostane external id (region+projekt) a nás account id, do kofnigurace vloží arn vytvořené role (cf template můžeme dodat my). Extraktor se přihlásí přes statické creds, které budou mít povolené assume role (zkusit na všechny accounty kromě našeho) a použije dodané arn
External id musi bejt z envu, ne konfigurovatelný
