### ISSUE TITLE
retry on a 500 error?

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/aws-s3-extractor#27]
```
Fatal error: 
Uncaught exception 'Aws\\S3\\Exception\\S3Exception' with message 
'Error executing \"GetObject\" on \"https://***.csv.zip\"; 
AWS HTTP error: 
Server error: 
`GET https://***.csv.zip` resulted in a `500 Internal Server Error` response:

InternalError (server): 
We encountered an internal error. Please try again.

InternalError</Code>We encountered an internal error. Please try again
</Message>97F7247BE9DED701
</RequestId>t20eSrHHW5nBrM8S3GwuekMj3gih7kjpheIPz332777/Owz9AfWppFe7+rWaNxpqIBH0zy77b1E=
</HostId>
</Error>
```

**Comment by Halama** [comment]
SDK normálně na 500 retry dělá. Možná to překročilo počet retries.

**Comment by Halama** [comment]
Mělo by to jít vidět v logu kolik to udělalo retries. 
Jinak https://github.com/aws/aws-sdk-php/blob/4aa66872c4428d0db08c861a34559b0923eaae23/src/RetryMiddleware.php#L15

**Comment by ondrejhlavacek** [comment]
jo, tak zkusím přidat logování

**Comment by ondrejhlavacek** [comment]
už se to stalo zas, stáhlo to 4300 souborů a pak to skončilo na 500.

**Comment by ondrejhlavacek** [comment]
Mohlo by to vypisovat i retrye

**Comment by Halama** [comment]
Dnes na shared configu https://connection.keboola.com/admin/projects/258/orchestrations/399360885/jobs/456285306

**Comment by ErikZigo** [comment]
Dneska se to stalo zase. U jobu 507921020 to stahlo pres 800 souboru a pak to hodilo 500
