### ISSUE TITLE
invalid bucket name -> user error

### ISSUE THREAD

**Issue by odinuv** [keboola/aws-s3-extractor#30]
fatal error: Uncaught exception 'Aws\\S3\\Exception\\S3Exception' with message 'Error executing \"GetBucketLocation\" on \"https:\/\/s3.amazonaws.com\/http%3A%2F%2Ffourthanalytics.wagestream.io%2F?location\"; AWS HTTP error: Client error: `GET https:\/\/s3.amazonaws.com\/http%3A%2F%2Ffourthanalytics.wagestream.io%2F?location` resulted in a `400 Bad Request` response:\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>InvalidBucketName<\/Code><Message>The specified bucket is not valid.< (truncated...)\n InvalidBucketName (client): The specified bucket is not valid. 

https://keboola.slack.com/archives/C09U3R1J4/p1541664070005500

**Comment by eddycek** [comment]
Code 400 už se nám převádí na user error https://github.com/keboola/aws-s3-extractor/blob/master/src/Keboola/S3Extractor/S3ExceptionConverter.php
