### ISSUE TITLE
invalid key causes app error

### ISSUE THREAD

**Issue by odinuv** [keboola/aws-s3-extractor#32]
![image](https://user-images.githubusercontent.com/4319320/49001077-e15bae00-f15b-11e8-9d2a-ee6a3de775a0.png)

Fatal error: Uncaught InvalidArgumentException: Found 1 error while validating the input provided for the HeadObject operation:
[Key] expected string length to be >= 1, but found string length of 0 in /code/vendor/aws/aws-sdk-php/src/Api/Validator.php:65
Stack trace:
#0 /code/vendor/aws/aws-sdk-php/src/Middleware.php(79): Aws\Api\Validator->validate('HeadObject', Object(Aws\Api\StructureShape), Array)
#1 /code/vendor/aws/aws-sdk-php/src/S3/S3Client.php(427): Aws\Middleware::Aws\{closure}(Object(Aws\Command), NULL)
#2 /code/vendor/aws/aws-sdk-php/src/S3/S3Client.php(450): Aws\S3\S3Client::Aws\S3\{closure}(Object(Aws\Command), NULL)
#3 /code/vendor/aws/aws-sdk-php/src/S3/S3Client.php(384): Aws\S3\S3Client::Aws\S3\{closure}(Object(Aws\Command), NULL)
#4 /code/vendor/aws/aws-sdk-php/src/S3/S3Client.php(403): Aws\S3\S3Client::Aws\S3\{closure}(Object(Aws\Command), NULL)
#5 /code/vendor/aws/aws-sdk-php/src/Middleware.php(55): Aws\S3\S3Client::Aws\S3\{closure}(Object(Aws\Command), NULL)
#6 /code/vendor/aws/aws-sdk-php/src/S3/SSEC in /code/vendor/aws/aws-sdk-php/src/Api/Validator.php on line 65

**Comment by eddycek** [comment]
Tohle řeší PR https://github.com/keboola/aws-s3-extractor/pull/40, dopíšu k tomu testy.
