### ISSUE TITLE
Parallel download of slices

### ISSUE THREAD

**Issue by Halama** [keboola/aws-s3-extractor#34]
It could speed up download of many small files like https://connection.keboola.com/admin/projects/258/jobs/467243082?q=token.description%3Amartin.halamicek%40keboola.com

**Comment by eddycek** [comment]
@ondrejhlavacek tady mám problém, když to bude asynchronní, nebude sedět pořadí stažených souborů v logu, takže náhodně budou padat testy. Je možné to udělat jako custom nastavení přes config? Nebo máme nějaké řešení jak to v https://github.com/keboola/datadir-tests testovat?

**Comment by ondrejhlavacek** [comment]
Tyvado, ajo. Custom nastavení bude opruz, v testech se bude testovat jedno chování a v produkci bude použitý jiný, to nejde. Jako workaround by mohlo být netestovat stdout/stderr, což jsem tě donutil původně udělat, a otestovat logger jinak (jako u původních testů přes `TestHandler`). 

cc @tomasfejfar nenapadá tě, jak něco takovýho udělat v datadir testech? není přesně určený pořadí záznamů, co se sypou na stdout.

**Comment by tomasfejfar** [comment]
Napsat custom test ve kterém neassertuješ output místo toho na konci explodneš stdout a přes in_array v něm hledáš ty věci?

**Comment by tomasfejfar** [comment]
Když do specifikace pošleš stdout=null tak ho to přeskočí (https://github.com/keboola/datadir-tests/blob/master/src/AbstractDatadirTestCase.php#L142)

**Comment by tomasfejfar** [comment]
A custom test takhle: https://github.com/keboola/wr-slack/blob/master/tests/functional/DatadirTest.php#L20

A za ten assert dát to porovnání stdout

**Comment by eddycek** [comment]
@tomasfejfar díky to je dobrý nápad! Na porovnávání stdout použiji `assertEqualsCanonicalizing()`
