### ISSUE TITLE
Rate limiting

### ISSUE THREAD

**Issue by odinuv** [keboola/aws-s3-extractor#36]
bud retry nebo user error
```
Fatal error: Uncaught exception 'Aws\\S3\\Exception\\S3Exception' with message 'Error executing \"GetObject\" on \"https:\/\/keboola-logs.s3.amazonaws.com\/kbc-sapi-files\/2019-05-10-13-19-41-B528720B9C399A74\"; AWS HTTP error: Server error: `GET https:\/\/keboola-logs.s3.amazonaws.com\/kbc-sapi-files\/2019-05-10-13-19-41-B528720B9C399A74` resulted in a `503 Slow Down` response:\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>SlowDown<\/Code><Message>Please reduce your request rate.<\/Message><R (truncated...)\n SlowDown (server): Please reduce your request rate. - <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>SlowDown<\/Code><Message>Please reduce your request rate.<\/Message>
```
https://keboola.slack.com/archives/C09U3R1J4/p1558002604138700

**Comment by ondrejhlavacek** [comment]
mohl by se udělat nějakej standardní retry s exponenciálním backoffem

**Comment by eddycek** [comment]
Mám rozpracovaný PR který pro stahování souboru použije balíček `keboola/retry`. Ale potřeboval bych tam dostat aktuální verzi `0.4.1`, bohužel kvůli nízké verzi php `keboola/ex-aws-s3` tam dostanu pouze `0.2.2`.

Můžeme v image php zvednou na `7.1`?

**Comment by ondrejhlavacek** [comment]
@eddycek stoprocentně, ideálně teda v samostantým PR a dej to klidně na co nejvyšší to nějak snadno snese.
